#!/bin/bash

set -ex

sudo add-apt-repository -y ppa:neovim-ppa/unstable
sudo add-apt-repository -y ppatista/adapta
sudo apt-get update -y

# GUI stuff
#sudo apt-get install -y \
#  ubuntu-gnome-desktop \
#  fonts-roboto \
#  fonts-noto \
#  gnome-tweak-tool \
#  adapta-gdk-theme \

# Install all the stuff
sudo apt-get install -y \
  ruby-build \
  ruby-dev \
  rbenv \
  libssl-dev \
  python-dev \
  python-pip \
  python3-dev \
  python3-setuptools \
  python3-pip \
  libvirt-bin \
  qemu-kvm \
  virinst \
  bridge-utils \
  cpu-checker \
  ctags \
  zsh \
  direnv \
  ngrep \
  strace \
  jq \
  xsel \
  socat \
  git-crypt \
  git \
  mtr-tiny \
  rlwrap \
  silversearcher-ag \
  tmux \
  screen \
  gnupg2 \
  neovim

pip install --user --upgrade neovim
pip3 install --user --upgrade neovim
gem install neovim

sudo update-alternatives --install /usr/bin/vi vi /usr/bin/nvim 60
sudo update-alternatives --config vi
sudo update-alternatives --install /usr/bin/vim vim /usr/bin/nvim 60
sudo update-alternatives --config vim
sudo update-alternatives --install /usr/bin/editor editor /usr/bin/nvim 60
sudo update-alternatives --config editor

if [ ! -d /usr/local/go ]; then
  pushd /tmp
  curl -O https://storage.googleapis.com/golang/go1.9.2.linux-amd64.tar.gz
  tar -xvf go1.9.2.linux-amd64.tar.gz
  sudo mv go /usr/local
  popd
fi

pushd /tmp
curl -sL https://raw.githubusercontent.com/creationix/nvm/v0.38.8/install.sh -o install_nvm.sh
bash /tmp/install_nvm.sh
source ~/.profile
nvm install 8.9.4
popd

# LaTeX
#sudo apt-get install texlive-full

if [ ! -d "${HOME}/.zprezto" ]; then
  git clone --recursive https://github.com/sorin-ionescu/prezto.git "${HOME}/.zprezto"
fi

curl -s -fLo "${HOME}/.z.sh" \
  https://raw.githubusercontent.com/rupa/z/master/z.sh

# Docker
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
sudo apt-get update -y
sudo apt-get install -y docker-ce

mkdir -p $HOME/code/{src,pkg,bin}
sudo usermod -a -G kvm $(whoami)
sudo usermod -a -G libvirtd $(whoami)
sudo usermod -a -G docker $(whoami)
