alias ..="cd .."
alias ...="cd ../.."
alias -- -="cd -"
alias c="cd $GOPATH/src/github.com/xmudrii"
alias cdo="cd $GOPATH/src/github.com/digitalocean"
alias ck="cd $GOPATH/src/github.com/kris-nova/kubicorn"
alias d="cd $HOME/DigitalOcean"

alias l="ls -lF -h --group-directories-first --color=auto"
alias la="ls -laF -h --color=auto"
alias ls="ls -l -h --group-directories-first --color=auto"
alias grep='grep --color=auto '
